カレンダープログラムを作成
yokonari/ruby-practices pull request #2
Opened 2021-11-07 02:07 UTC by yokonari

2021-11-11 05:47 UTC, komagata requested changes
このPRにfizzbuzzプログラムも含まれてしまっているようです〜

2021-11-13 01:54 UTC, yokonari commented
FizzBuzzのコミットをrevertで取り消しました。
お手数おかけしてすみません…😭

2021-11-13 16:46 UTC, komagata commented
Revertは基本修正には使いません。revertのためだけに余計なcommitができてしまっているのでrebaseやresetなどを調べて、過去の不要なコミットを削除してみてください〜

2021-11-13 23:27 UTC, yokonari commented
了解しました🙏
rebaseで不要なコミットを削除しました。

2021-11-15 05:46 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-11-15 05:46 UTC, komagata commented on 02.calendar/cal
> +year = (options["y"] || Date.today.year).to_i
一行で分かりやすくまとまっていて良いですね！

2021-11-15 10:51 UTC, merged